# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ site ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
          retention-days: 1
      
      
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --all
          git checkout site
      - run: |
          rm -rf *
          echo "Remove old deployment"
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - run: |
          git config --global user.email "karthick2021@gmail.com"
          git config --global user.name "karthick-2021"
          echo "Updated author name"
      - run: |
          git add .
          git commit -m "Automated commit from github actions. ID = ${{ github.run_id }}"
          git push origin site 
          echo Deployed the latest changes
